apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ioqf4wm0c-java-quarkus
  janus-idp.io/tekton: ioqf4wm0c-java-quarkus
  backstage.io/kubernetes-id: ioqf4wm0c-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ioqf4wm0c-java-quarkus
resources:
- deployment.yaml
- route.yaml
- service.yaml
